# Generated by Django 3.0.8 on 2020-08-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParametrageTache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelleTache_text', models.CharField(max_length=120)),
                ('tempsMoyenTraitementH_int', models.IntegerField(default=0)),
                ('delaisJTolerance', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom_text', models.CharField(max_length=32)),
                ('nom_text', models.CharField(max_length=32)),
                ('estActif_bool', models.BooleanField(default=True)),
                ('metier_text', models.CharField(max_length=50)),
                ('pourcentageAttribution_int', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tache_text', models.CharField(max_length=120)),
                ('creation_date', models.DateTimeField(verbose_name='Date de création')),
                ('jalon_date', models.DateTimeField(verbose_name='Date Jalon de réalisation')),
                ('commentaire_text', models.CharField(max_length=600)),
                ('priseEnChargePar_id', models.CharField(max_length=9)),
                ('creerPar_id', models.CharField(max_length=9)),
                ('urgence_bool', models.BooleanField(default=False)),
                ('codeTache_text', models.CharField(max_length=3)),
            ],
        ),
    ]
