# Generated by Django 3.0.8 on 2020-08-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeManager', '0002_auto_20200801_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametragetache',
            name='tempsMoyenTraitementH_int',
            field=models.TimeField(verbose_name='Temps de traitement'),
        ),
    ]
