# Generated by Django 3.0.8 on 2020-08-01 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeManager', '0004_auto_20200801_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='creerPar_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tache',
            name='priseEnChargePar_id',
            field=models.IntegerField(default=999999999),
        ),
    ]
