# Generated by Django 3.0.8 on 2020-08-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeManager', '0005_auto_20200801_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='etat_text',
            field=models.CharField(default='EC', max_length=2),
        ),
    ]
