# Generated by Django 3.0.8 on 2020-08-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeManager', '0006_tache_etat_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='adresseMail_text',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
