# Generated by Django 3.0.8 on 2020-11-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeManager', '0010_auto_20201102_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='attestationinfos',
            name='username_text',
            field=models.CharField(default=' ', max_length=32),
        ),
    ]
